
-- Seed data transformed from Isomorphic VSAM simulation data.
-- Field names mapped through domain model provenance.
-- Values converted from COBOL format to native SQL types.


-- frozen_agency_adjustments

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000001', 0, 0, 0, 0, 0, 0, 0, 0.00, 0, 0, 0, 0.00, '10001', 0.000, 0, 0, 0, 0);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000002', 1, 1, 1, 1, 1, 1, 1, 0.01, 1, 1, 1, 0.01, '12001', 0.001, 1, 1, 1, 1);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000003', 5, 5, 5, 5, 5, 5, 5, 0.05, 5, 5, 5, 0.05, '13001', 0.005, 5, 5, 5, 5);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000004', 6, 6, 6, 6, 6, 6, 6, 0.06, 6, 6, 6, 0.06, '14001', 0.006, 6, 6, 6, 6);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000005', 2, 2, 2, 2, 2, 2, 2, 0.02, 2, 2, 2, 0.02, '20001', 0.002, 2, 2, 2, 2);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000006', 7, 7, 7, 7, 7, 7, 7, 0.07, 7, 7, 7, 0.07, '22001', 0.007, 7, 7, 7, 7);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000007', 3, 3, 3, 3, 3, 3, 3, 0.03, 3, 3, 3, 0.03, '37001', 0.003, 3, 3, 3, 3);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000011', 11, 11, 11, 11, 11, 11, 11, 0.11, 11, 11, 11, 0.11, '71001', 0.011, 11, 11, 11, 11);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000012', 12, 12, 12, 12, 12, 12, 12, 0.12, 12, 12, 12, 0.12, '76001', 0.012, 12, 12, 12, 12);

INSERT INTO frozen_agency_adjustments (agency_number, annexed_assessed_value, annexed_equalized_value, current288_value, disconnected_assessed_value, disconnected_equalized_value, expired288_value, expired_incentive_equalized_value, expired_incentive_tax_amount, expired_incentive_value, first_time_value, frozen_equalized_value, frozen_tax_amount, tax_code, tax_rate, tif_current_equalized_value, tif_difference_equalized_value, tif_prior_frozen_equalized_value, total_frozen_value) VALUES ('000000020', 4, 4, 4, 4, 4, 4, 4, 0.04, 4, 4, 4, 0.04, '77001', 0.004, 4, 4, 4, 4);


