

CREATE TABLE homeowner_exemptions (
    id BIGSERIAL PRIMARY KEY,
    application_year INTEGER,
    assessed_value BIGINT,
    assessment_class INTEGER,
    certificate_of_error_number INTEGER,
    city VARCHAR(12),
    clerks_class INTEGER,
    cooperative_quantity INTEGER,
    eligibility_indicator INTEGER,
    equalization_factor DECIMAL(5,4),
    equalized_value BIGINT,
    exemption_type INTEGER,
    key_parcel_number BIGINT,
    mailing_address VARCHAR(22),
    occupancy_factor DECIMAL(5,1),
    owner_name VARCHAR(22),
    property_number BIGINT,
    proration DECIMAL(7,6),
    record_code INTEGER,
    response_status INTEGER,
    secondary_response_status INTEGER,
    split_code INTEGER,
    state VARCHAR(2),
    tax_code INTEGER,
    tax_type INTEGER,
    tertiary_status INTEGER,
    volume_number INTEGER,
    zip_code BIGINT
);


CREATE TABLE homeowner_masters (
    id BIGSERIAL PRIMARY KEY,
    application_year INTEGER,
    assessed_value BIGINT,
    assessment_class INTEGER,
    certificate_of_error_number INTEGER,
    city VARCHAR(12),
    cooperative_quantity INTEGER,
    equalization_factor DECIMAL(5,4),
    equalized_value BIGINT,
    exemption_type INTEGER,
    mailing_address VARCHAR(22),
    nphe_amount BIGINT,
    nphe_base_year INTEGER,
    nphe_status VARCHAR(2),
    occupancy_factor DECIMAL(5,1),
    owner_name VARCHAR(22),
    property_number BIGINT,
    proration DECIMAL(7,6),
    response_status INTEGER,
    secondary_response_status INTEGER,
    state VARCHAR(2),
    tax_code INTEGER,
    tax_type INTEGER,
    temporary_assessed_value BIGINT,
    tertiary_status INTEGER,
    volume_number INTEGER,
    zip_code BIGINT
);


CREATE TABLE maintained_homestead_exemptions (
    id BIGSERIAL PRIMARY KEY,
    application_year INTEGER,
    assessed_value BIGINT,
    assessment_class INTEGER,
    certificate_of_error_number INTEGER,
    city VARCHAR(12),
    clerks_class INTEGER,
    cooperative_quantity INTEGER,
    equalization_factor DECIMAL(5,4),
    equalized_value BIGINT,
    exemption_type INTEGER,
    mailing_address VARCHAR(22),
    nphe_amount BIGINT,
    nphe_base_year INTEGER,
    nphe_status VARCHAR(2),
    occupancy_factor DECIMAL(5,1),
    owner_name VARCHAR(22),
    property_number BIGINT,
    proration DECIMAL(7,6),
    response_status INTEGER,
    secondary_response_status INTEGER,
    state VARCHAR(2),
    tax_code INTEGER,
    tax_type VARCHAR(1),
    tertiary_status INTEGER,
    volume_number INTEGER,
    zip_code BIGINT
);


CREATE TABLE senior_freeze_applicants (
    id BIGSERIAL PRIMARY KEY,
    age INTEGER,
    applicant_address VARCHAR(22),
    applicant_city VARCHAR(12),
    applicant_first_name VARCHAR(15),
    applicant_last_name VARCHAR(20),
    applicant_middle_initial VARCHAR(1),
    applicant_old_name VARCHAR(22),
    applicant_state VARCHAR(2),
    applicant_title VARCHAR(2),
    applicant_zip_code BIGINT,
    base_year INTEGER,
    base_year_eligible_equalized_value BIGINT,
    base_year_indicator VARCHAR(1),
    batch_number INTEGER,
    birth_date VARCHAR(8),
    civil_service_benefits DECIMAL(9,2),
    cooperative_senior_shares INTEGER,
    denial_date INTEGER,
    first_application_date INTEGER,
    homeowner_base_year INTEGER,
    homeowner_base_year_assessed_value BIGINT,
    homeowner_base_year_equalization_factor DECIMAL(5,4),
    homeowner_base_year_equalized_value BIGINT,
    homeowner_eligibility_indicator INTEGER,
    homeowner_status VARCHAR(1),
    homestead_batch_number INTEGER,
    homestead_percent_shares DECIMAL(6,3),
    homestead_shares INTEGER,
    homestead_status VARCHAR(1),
    homestead_year_applied INTEGER,
    interest_income DECIMAL(9,2),
    last_application_date INTEGER,
    life_care_facility_indicator VARCHAR(1),
    maintenance_indicator INTEGER,
    name_maintenance_indicator INTEGER,
    net_capital_gain DECIMAL(9,2),
    net_rental_income DECIMAL(9,2),
    no_income_indicator VARCHAR(1),
    notarized_indicator VARCHAR(1),
    other_benefits DECIMAL(9,2),
    other_income DECIMAL(9,2),
    percent_senior_shares DECIMAL(6,6),
    phone_number BIGINT,
    public_aid DECIMAL(9,2),
    qualification_date INTEGER,
    railroad_benefits DECIMAL(9,2),
    returned_date INTEGER,
    senior_freeze_percent DECIMAL(2,1),
    senior_freeze_status VARCHAR(1),
    signed_indicator VARCHAR(1),
    social_security_income DECIMAL(9,2),
    social_security_number BIGINT,
    total_income DECIMAL(9,2),
    veterans_benefits DECIMAL(9,2),
    wages DECIMAL(9,2)
);


CREATE TABLE senior_freeze_masters (
    id BIGSERIAL PRIMARY KEY,
    base_value_manual_calculation_indicator VARCHAR(1),
    base_value_no_calculation_indicator VARCHAR(1),
    base_value_year INTEGER,
    base_value_year_class INTEGER,
    base_year_eligible_computed_full_assessed_value BIGINT,
    base_year_equalized_value BIGINT,
    base_year_full_assessed_value BIGINT,
    base_year_total_eligible_computed_equalized_value BIGINT,
    building_shares INTEGER,
    building_units INTEGER,
    calculation_type VARCHAR(1),
    class288_expiration_assessed_value BIGINT,
    class288_expiration_equalized_value BIGINT,
    class288_over_limit_assessed_value BIGINT,
    class288_over_limit_equalized_value BIGINT,
    current_year_class INTEGER,
    current_year_eligible_computed_assessed_value BIGINT,
    current_year_eligible_computed_equalized_value BIGINT,
    current_year_farm_indicator VARCHAR(1),
    current_year_final_equalized_value_difference BIGINT,
    current_year_full_assessed_value BIGINT,
    current_year_full_equalized_value BIGINT,
    current_year_not_eligible_assessed_value BIGINT,
    current_year_not_eligible_equalized_value BIGINT,
    homeowner_units INTEGER,
    homestead_units INTEGER,
    key_parcel_number BIGINT,
    mailing_city VARCHAR(28),
    mailing_direction VARCHAR(2),
    mailing_house_number VARCHAR(5),
    mailing_state VARCHAR(2),
    mailing_street VARCHAR(22),
    mailing_suffix VARCHAR(4),
    mailing_zip_code BIGINT,
    maintenance_indicator INTEGER,
    master_name VARCHAR(50),
    occupancy_factor DECIMAL(5,1),
    original_base_value_year INTEGER,
    original_base_year_eligible_computed_full_assessed_value BIGINT,
    original_base_year_equalized_value BIGINT,
    original_base_year_full_assessed_value BIGINT,
    original_base_year_total_eligible_computed_equalized_value BIGINT,
    original_current_year_final_equalized_value_difference BIGINT,
    original_manual_calculation_indicator VARCHAR(1),
    property_proration DECIMAL(7,6),
    record_code VARCHAR(1),
    senior_freeze_shares INTEGER,
    split_code INTEGER
);



