
-- Seed data transformed from Isomorphic VSAM simulation data.
-- Field names mapped through domain model provenance.
-- Values converted from COBOL format to native SQL types.


-- homeowner_masters

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (0, 100000, 202, 0, 'CHICAGO', 1, 0.0, 100000, 0, '101 MAIN ST', 0, 0, 'SA', 0.0, 'ALICE OWNER', 10011000010000, 1.0, 0, 0, 'IL', 10001, 0, 0, 0, 1, 60601);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (1, 125000, 203, 1, 'CHICAGO', 1, 0.0001, 125000, 3, '202 OAK AVE', 1, 1, 'CO', 0.1, 'BOB RENEWED', 12022000020000, 1.05, 1, 1, 'IL', 12001, 0, 1, 1, 9, 60602);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (3, 175000, 201, 3, 'CHICAGO', 1, 0.0003, 175000, 4, '606 FOREST AVE', 3, 3, 'TR', 0.3, 'FIONA NORTH', 13066000060000, 0.95, 2, 0, 'IL', 13001, 1, 3, 3, 25, 60068);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (4, 325000, 212, 4, 'CHICAGO', 1, 0.0004, 325000, 5, '707 RIDGE BLVD', 4, 4, 'DI', 0.4, 'GEORGE URBAN', 14077000070000, 1.15, 3, 1, 'IL', 14001, 2, 4, 4, 36, 60201);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (2, 250000, 295, 2, 'CHICAGO', 1, 0.0002, 250000, 0, '303 LAKE ST', 2, 2, 'SA', 0.2, 'CAROL COOK', 20033000030000, 1.1, 4, 0, 'IL', 20001, 0, 2, 2, 63, 60603);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (6, 750000, 241, 6, 'CHICAGO', 1, 0.0006, 750000, 3, '808 CANAL ST', 6, 6, 'CO', 0.6, 'HARBOR WORKS', 22055000050000, 1.2, 0, 1, 'IL', 22001, 3, 6, 6, 86, 60607);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (5, 50000, 299, 5, 'CHICAGO', 12, 0.0005, 50000, 5, '404 STATE ST', 5, 5, 'TR', 0.5, 'DELTA COOP', 37044000040000, 0.5, 1, 0, 'IL', 37001, 0, 5, 5, 193, 60604);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (7, 80000, 278, 7, 'CHICAGO', 1, 0.0007, 80000, 5, '909 COURT PL', 7, 7, 'DI', 0.7, 'IVY MUNICIPAL', 71011100110000, 0.8, 2, 1, 'IL', 71001, 5, 7, 7, 350, 60426);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (8, 110000, 297, 8, 'CHICAGO', 1, 0.0008, 110000, 0, '1010 PRAIRIE RD', 8, 8, 'SA', 0.8, 'JAMES RENEWAL', 76022200120000, 1.25, 3, 0, 'IL', 76001, 0, 8, 8, 508, 60473);

INSERT INTO homeowner_masters (application_year, assessed_value, assessment_class, certificate_of_error_number, city, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, temporary_assessed_value, tertiary_status, volume_number, zip_code) VALUES (9, 90000, 234, 9, 'CHICAGO', 1, 0.0009, 90000, 3, '505 PINE RD', 9, 9, 'CO', 0.9, 'ED SENIOR', 77033300130000, 0.75, 4, 1, 'IL', 77001, 0, 9, 9, 528, 60605);



-- homeowner_exemptions

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (0, 100000, 202, 0, 'CHICAGO', 9, 1, 0, 0.0, 100000, 0, 10011000010000, '101 MAIN ST', 0.0, 'ALICE OWNER', 10011000010000, 1.0, 0, 0, 0, 0, 'IL', 10001, 0, 0, 1, 60601);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (1, 125000, 203, 1, 'CHICAGO', 9, 1, 1, 0.0001, 125000, 3, 12022000020000, '202 OAK AVE', 0.1, 'BOB RENEWED', 12022000020000, 1.05, 1, 1, 1, 1, 'IL', 12001, 0, 1, 9, 60602);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (3, 175000, 201, 3, 'CHICAGO', 9, 1, 0, 0.0003, 175000, 4, 13066000060000, '606 FOREST AVE', 0.3, 'FIONA NORTH', 13066000060000, 0.95, 3, 2, 0, 3, 'IL', 13001, 1, 3, 25, 60068);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (4, 325000, 212, 4, 'CHICAGO', 9, 1, 1, 0.0004, 325000, 5, 14077000070000, '707 RIDGE BLVD', 0.4, 'GEORGE URBAN', 14077000070000, 1.15, 4, 3, 1, 4, 'IL', 14001, 2, 4, 36, 60201);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (2, 250000, 295, 2, 'CHICAGO', 9, 1, 0, 0.0002, 250000, 0, 20033000030000, '303 LAKE ST', 0.2, 'CAROL COOK', 20033000030000, 1.1, 2, 4, 0, 2, 'IL', 20001, 0, 2, 63, 60603);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (6, 750000, 241, 6, 'CHICAGO', 9, 1, 1, 0.0006, 750000, 3, 22055000050000, '808 CANAL ST', 0.6, 'HARBOR WORKS', 22055000050000, 1.2, 6, 0, 1, 6, 'IL', 22001, 3, 6, 86, 60607);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (5, 50000, 299, 5, 'CHICAGO', 9, 12, 0, 0.0005, 50000, 5, 37044000040000, '404 STATE ST', 0.5, 'DELTA COOP', 37044000040000, 0.5, 5, 1, 0, 5, 'IL', 37001, 0, 5, 193, 60604);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (7, 80000, 278, 7, 'CHICAGO', 9, 1, 1, 0.0007, 80000, 5, 71011100110000, '909 COURT PL', 0.7, 'IVY MUNICIPAL', 71011100110000, 0.8, 7, 2, 1, 7, 'IL', 71001, 5, 7, 350, 60426);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (8, 110000, 297, 8, 'CHICAGO', 9, 1, 0, 0.0008, 110000, 0, 76022200120000, '1010 PRAIRIE RD', 0.8, 'JAMES RENEWAL', 76022200120000, 1.25, 8, 3, 0, 8, 'IL', 76001, 0, 8, 508, 60473);

INSERT INTO homeowner_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, eligibility_indicator, equalization_factor, equalized_value, exemption_type, key_parcel_number, mailing_address, occupancy_factor, owner_name, property_number, proration, record_code, response_status, secondary_response_status, split_code, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (9, 90000, 234, 9, 'CHICAGO', 9, 1, 1, 0.0009, 90000, 3, 77033300130000, '505 PINE RD', 0.9, 'ED SENIOR', 77033300130000, 0.75, 9, 4, 1, 9, 'IL', 77001, 0, 9, 528, 60605);



-- maintained_homestead_exemptions

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (25, 100000, 202, 0, 'CHICAGO', 0, 1, 1.2345, 123450, 3, '101 MAIN ST', 6000, 2024, '', 100.0, 'ALICE OWNER', 100000000000001, 1.0, 0, 0, 'IL', 10001, '0', 0, 101, 606010001);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (25, 100000, 203, 0, 'EVANSTON', 0, 1, 1.2345, 123450, 3, '202 OAK AVE', 6000, 2024, '', 100.0, 'BOB RENEWED', 100000000000002, 1.0, 1, 1, 'IL', 10002, '0', 0, 101, 606010001);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (25, 100000, 295, 0, 'SKOKIE', 0, 1, 1.2345, 123450, 3, '303 PINE RD', 6000, 2024, '', 87.5, 'CAROL NO', 100000000000003, 1.0, 2, 0, 'IL', 10001, '0', 0, 101, 606010001);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (25, 100000, 234, 0, 'CHICAGO', 0, 12, 1.2345, 123450, 5, '404 LAKE SHORE DR', 6000, 2024, '', 100.0, 'DELTA COOP', 100000000000004, 1.0, 0, 0, 'IL', 10001, '0', 0, 101, 606010001);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (25, 100000, 299, 0, 'CHICAGO', 0, 1, 1.2345, 123450, 3, '999 LAST ST', 6000, 2024, '', 100.0, 'END SENTINEL OWNER', 999999999999999, 1.0, 4, 0, 'IL', 77001, '0', 0, 101, 606010001);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (26, 175000, 201, 3, 'CHICAGO', 9, 3, 0.0003, 175000, 3, '606 FOREST AVE', 3, 3, 'N', 0.3, 'FIONA NORTH', 13066000060000, 3e-6, 3, 3, 'IL', 13001, 'N', 3, 25, 60068);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (27, 325000, 212, 4, 'CHICAGO', 9, 4, 0.0004, 325000, 4, '707 RIDGE BLVD', 4, 4, 'Y', 0.4, 'GEORGE URBAN', 14077000070000, 4e-6, 4, 4, 'IL', 14001, 'M', 4, 36, 60201);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (28, 750000, 241, 6, 'CHICAGO', 9, 6, 0.0006, 750000, 6, '808 CANAL ST', 6, 6, 'A', 0.6, 'HARBOR WORKS', 22055000050000, 6e-6, 6, 6, 'IL', 22001, 'I', 6, 86, 60607);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (29, 80000, 278, 7, 'CHICAGO', 9, 7, 0.0007, 80000, 7, '909 COURT PL', 7, 7, 'E', 0.7, 'IVY MUNICIPAL', 71011100110000, 7e-6, 7, 7, 'IL', 71001, 'G', 7, 350, 60426);

INSERT INTO maintained_homestead_exemptions (application_year, assessed_value, assessment_class, certificate_of_error_number, city, clerks_class, cooperative_quantity, equalization_factor, equalized_value, exemption_type, mailing_address, nphe_amount, nphe_base_year, nphe_status, occupancy_factor, owner_name, property_number, proration, response_status, secondary_response_status, state, tax_code, tax_type, tertiary_status, volume_number, zip_code) VALUES (30, 110000, 297, 8, 'CHICAGO', 9, 8, 0.0008, 110000, 8, '1010 PRAIRIE RD', 8, 8, 'F', 0.8, 'JAMES RENEWAL', 76022200120000, 8e-6, 8, 8, 'IL', 76001, 'F', 8, 508, 60473);



-- senior_freeze_masters

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('B', 'B', 9999, 0, 0, 0, 0, 0, 0, 0, 'R', 0, 0, 0, 0, 0, 0, 0, 'B', 0, 0, 0, 0, 0, 0, 0, 10011000010000, 'CHICAGO', 'BA', 'BASEL', 'IL', '101 MAIN ST', 'BASE', 60601, 0, 'ALICE OWNER', 0.0, 9999, 0, 0, 0, 0, 0, 'B', 1.0, 'A', 0, 0);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('R', 'R', 9999, 1, 1, 1, 1, 1, 1, 1, 'H', 1, 1, 1, 1, 1, 1, 1, 'R', 1, 1, 1, 1, 1, 1, 1, 12022000020000, 'CHICAGO', 'RE', 'RESID', 'IL', '202 OAK AVE', 'RESI', 60602, 1, 'BOB RENEWED', 0.1, 9999, 1, 1, 1, 1, 1, 'R', 1.05, 'B', 1, 1);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('C', 'C', 9999, 2, 2, 2, 2, 2, 2, 2, 'C', 2, 2, 2, 2, 2, 2, 2, 'C', 2, 2, 2, 2, 2, 2, 2, 20033000030000, 'CHICAGO', 'CO', 'COMME', 'IL', '303 LAKE ST', 'COMM', 60603, 2, 'CAROL COOK', 0.2, 9999, 2, 2, 2, 2, 2, 'C', 1.1, 'C', 2, 2);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('E', 'E', 9999, 5, 5, 5, 5, 5, 5, 5, 'E', 5, 5, 5, 5, 5, 5, 5, 'E', 5, 5, 5, 5, 5, 5, 5, 37044000040000, 'CHICAGO', 'EX', 'EXEMP', 'IL', '404 STATE ST', 'EXEM', 60604, 5, 'DELTA COOP', 0.5, 9999, 5, 5, 5, 5, 5, 'E', 0.5, 'D', 5, 5);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('S', 'S', 9999, 9, 9, 9, 9, 9, 9, 9, 'S', 9, 9, 9, 9, 9, 9, 9, 'S', 9, 9, 9, 9, 9, 9, 9, 77033300130000, 'CHICAGO', 'SE', 'SENIO', 'IL', '505 PINE RD', 'SENI', 60605, 9, 'ED SENIOR', 0.9, 9999, 9, 9, 9, 9, 9, 'S', 0.75, 'E', 9, 9);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('N', 'N', 9999, 3, 3, 3, 3, 3, 3, 3, 'N', 3, 3, 3, 3, 3, 3, 3, 'N', 3, 3, 3, 3, 3, 3, 3, 13066000060000, 'CHICAGO', 'NO', 'NORTH', 'IL', '606 FOREST AVE', 'NORT', 60068, 3, 'FIONA NORTH', 0.3, 9999, 3, 3, 3, 3, 3, 'N', 0.95, 'F', 3, 3);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('M', 'M', 9999, 4, 4, 4, 4, 4, 4, 4, 'M', 4, 4, 4, 4, 4, 4, 4, 'M', 4, 4, 4, 4, 4, 4, 4, 14077000070000, 'CHICAGO', 'MU', 'MULTI', 'IL', '707 RIDGE BLVD', 'MULT', 60201, 4, 'GEORGE URBAN', 0.4, 9999, 4, 4, 4, 4, 4, 'M', 1.15, 'G', 4, 4);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('I', 'I', 9999, 6, 6, 6, 6, 6, 6, 6, 'I', 6, 6, 6, 6, 6, 6, 6, 'I', 6, 6, 6, 6, 6, 6, 6, 22055000050000, 'CHICAGO', 'IN', 'INDUS', 'IL', '808 CANAL ST', 'INDU', 60607, 6, 'HARBOR WORKS', 0.6, 9999, 6, 6, 6, 6, 6, 'I', 1.2, 'H', 6, 6);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('M', 'M', 9999, 7, 7, 7, 7, 7, 7, 7, 'G', 7, 7, 7, 7, 7, 7, 7, 'M', 7, 7, 7, 7, 7, 7, 7, 71011100110000, 'CHICAGO', 'MU', 'MUNIC', 'IL', '909 COURT PL', 'MUNI', 60426, 7, 'IVY MUNICIPAL', 0.7, 9999, 7, 7, 7, 7, 7, 'M', 0.8, 'I', 7, 7);

INSERT INTO senior_freeze_masters (base_value_manual_calculation_indicator, base_value_no_calculation_indicator, base_value_year, base_value_year_class, base_year_eligible_computed_full_assessed_value, base_year_equalized_value, base_year_full_assessed_value, base_year_total_eligible_computed_equalized_value, building_shares, building_units, calculation_type, class288_expiration_assessed_value, class288_expiration_equalized_value, class288_over_limit_assessed_value, class288_over_limit_equalized_value, current_year_class, current_year_eligible_computed_assessed_value, current_year_eligible_computed_equalized_value, current_year_farm_indicator, current_year_final_equalized_value_difference, current_year_full_assessed_value, current_year_full_equalized_value, current_year_not_eligible_assessed_value, current_year_not_eligible_equalized_value, homeowner_units, homestead_units, key_parcel_number, mailing_city, mailing_direction, mailing_house_number, mailing_state, mailing_street, mailing_suffix, mailing_zip_code, maintenance_indicator, master_name, occupancy_factor, original_base_value_year, original_base_year_eligible_computed_full_assessed_value, original_base_year_equalized_value, original_base_year_full_assessed_value, original_base_year_total_eligible_computed_equalized_value, original_current_year_final_equalized_value_difference, original_manual_calculation_indicator, property_proration, record_code, senior_freeze_shares, split_code) VALUES ('S', 'S', 9999, 8, 8, 8, 8, 8, 8, 8, 'F', 8, 8, 8, 8, 8, 8, 8, 'S', 8, 8, 8, 8, 8, 8, 8, 76022200120000, 'CHICAGO', 'SE', 'SENIO', 'IL', '1010 PRAIRIE RD', 'SENI', 60473, 8, 'JAMES RENEWAL', 0.8, 9999, 8, 8, 8, 8, 8, 'S', 1.25, 'J', 8, 8);



-- senior_freeze_applicants

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (0, '101 MAIN ST', 'CHICAGO', 'BASELINE PARCEL', 'BASELINE PARCEL', 'B', 'BASELINE PARCEL', 'IL', 'BA', 60601, 2021, 100000, 'N', 0, '19500001', 0.0, 0, 0, 0, 0, 0, 0.0, 0, 0, 'N', 0, 1.0, 0, 'N', 0, 0.0, 0, 'B', 0, 0, 0.0, 0.0, 'B', 'B', 0.0, 0.0, 0.999999, 0, 0.0, 0, 0.0, 0, 0.0, 'N', 'B', 0.0, 0, 0.0, 0.0, 0.0);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (1, '202 OAK AVE', 'CHICAGO', 'RESIDENTIAL PAR', 'RESIDENTIAL PARCEL', 'R', 'RESIDENTIAL PARCEL', 'IL', 'RE', 60602, 2022, 125000, 'Y', 1, '19500002', 0.01, 1, 1, 1, 1, 1, 0.0001, 1, 1, 'Y', 1, 1.05, 1, 'Y', 1, 0.01, 1, 'R', 1, 1, 0.01, 0.01, 'R', 'R', 0.01, 0.01, 0.999999, 1, 0.01, 1, 0.01, 1, 0.1, 'Y', 'R', 0.01, 1, 0.01, 0.01, 0.01);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (2, '303 LAKE ST', 'CHICAGO', 'COMMERCIAL PARC', 'COMMERCIAL PARCEL', 'C', 'COMMERCIAL PARCEL', 'IL', 'CO', 60603, 2023, 250000, 'A', 2, '19500003', 0.02, 2, 2, 2, 2, 2, 0.0002, 2, 2, 'A', 2, 1.1, 2, 'A', 2, 0.02, 2, 'C', 2, 2, 0.02, 0.02, 'C', 'C', 0.02, 0.02, 0.999999, 2, 0.02, 2, 0.02, 2, 0.2, 'A', 'C', 0.02, 2, 0.02, 0.02, 0.02);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (5, '404 STATE ST', 'CHICAGO', 'EXEMPT PARCEL', 'EXEMPT PARCEL', 'E', 'EXEMPT PARCEL', 'IL', 'EX', 60604, 2024, 50000, 'E', 5, '19500004', 0.05, 5, 5, 5, 5, 5, 0.0005, 5, 5, 'E', 5, 0.5, 5, 'E', 5, 0.05, 5, 'E', 5, 5, 0.05, 0.05, 'E', 'E', 0.05, 0.05, 0.5, 5, 0.05, 5, 0.05, 5, 0.5, 'E', 'E', 0.05, 5, 0.05, 0.05, 0.05);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (9, '505 PINE RD', 'CHICAGO', 'SENIOR-FREEZE P', 'SENIOR-FREEZE PARCEL', 'S', 'SENIOR-FREEZE PARCEL', 'IL', 'SE', 60605, 2025, 90000, 'F', 9, '19500005', 0.09, 9, 9, 9, 9, 9, 0.0009, 9, 9, 'F', 9, 0.75, 9, 'F', 9, 0.09, 9, 'S', 9, 9, 0.09, 0.09, 'S', 'S', 0.09, 0.09, 0.75, 9, 0.09, 9, 0.09, 9, 0.9, 'F', 'S', 0.09, 9, 0.09, 0.09, 0.09);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (3, '606 FOREST AVE', 'CHICAGO', 'NORTH SUBURBAN', 'NORTH SUBURBAN PARCE', 'N', 'NORTH SUBURBAN PARCEL', 'IL', 'NO', 60068, 2026, 175000, 'N', 3, '19500006', 0.03, 3, 3, 3, 3, 3, 0.0003, 3, 3, 'N', 3, 0.95, 3, 'N', 3, 0.03, 3, 'N', 3, 3, 0.03, 0.03, 'N', 'N', 0.03, 0.03, 0.95, 3, 0.03, 3, 0.03, 3, 0.3, 'N', 'N', 0.03, 3, 0.03, 0.03, 0.03);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (4, '707 RIDGE BLVD', 'CHICAGO', 'MULTIFAMILY PAR', 'MULTIFAMILY PARCEL', 'M', 'MULTIFAMILY PARCEL', 'IL', 'MU', 60201, 2027, 325000, 'Y', 4, '19500007', 0.04, 4, 4, 4, 4, 4, 0.0004, 4, 4, 'Y', 4, 1.15, 4, 'Y', 4, 0.04, 4, 'M', 4, 4, 0.04, 0.04, 'M', 'M', 0.04, 0.04, 0.999999, 4, 0.04, 4, 0.04, 4, 0.4, 'Y', 'M', 0.04, 4, 0.04, 0.04, 0.04);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (6, '808 CANAL ST', 'CHICAGO', 'INDUSTRIAL PARC', 'INDUSTRIAL PARCEL', 'I', 'INDUSTRIAL PARCEL', 'IL', 'IN', 60607, 2028, 750000, 'A', 6, '19500008', 0.06, 6, 6, 6, 6, 6, 0.0006, 6, 6, 'A', 6, 1.2, 6, 'A', 6, 0.06, 6, 'I', 6, 6, 0.06, 0.06, 'I', 'I', 0.06, 0.06, 0.999999, 6, 0.06, 6, 0.06, 6, 0.6, 'A', 'I', 0.06, 6, 0.06, 0.06, 0.06);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (7, '909 COURT PL', 'CHICAGO', 'MUNICIPAL PARCE', 'MUNICIPAL PARCEL', 'M', 'MUNICIPAL PARCEL', 'IL', 'MU', 60426, 2029, 80000, 'E', 7, '19500009', 0.07, 7, 7, 7, 7, 7, 0.0007, 7, 7, 'E', 7, 0.8, 7, 'E', 7, 0.07, 7, 'M', 7, 7, 0.07, 0.07, 'M', 'M', 0.07, 0.07, 0.8, 7, 0.07, 7, 0.07, 7, 0.7, 'E', 'M', 0.07, 7, 0.07, 0.07, 0.07);

INSERT INTO senior_freeze_applicants (age, applicant_address, applicant_city, applicant_first_name, applicant_last_name, applicant_middle_initial, applicant_old_name, applicant_state, applicant_title, applicant_zip_code, base_year, base_year_eligible_equalized_value, base_year_indicator, batch_number, birth_date, civil_service_benefits, cooperative_senior_shares, denial_date, first_application_date, homeowner_base_year, homeowner_base_year_assessed_value, homeowner_base_year_equalization_factor, homeowner_base_year_equalized_value, homeowner_eligibility_indicator, homeowner_status, homestead_batch_number, homestead_percent_shares, homestead_shares, homestead_status, homestead_year_applied, interest_income, last_application_date, life_care_facility_indicator, maintenance_indicator, name_maintenance_indicator, net_capital_gain, net_rental_income, no_income_indicator, notarized_indicator, other_benefits, other_income, percent_senior_shares, phone_number, public_aid, qualification_date, railroad_benefits, returned_date, senior_freeze_percent, senior_freeze_status, signed_indicator, social_security_income, social_security_number, total_income, veterans_benefits, wages) VALUES (8, '1010 PRAIRIE RD', 'CHICAGO', 'SENIOR RENEWAL', 'SENIOR RENEWAL PARCE', 'S', 'SENIOR RENEWAL PARCEL', 'IL', 'SE', 60473, 2030, 110000, 'F', 8, '19500010', 0.08, 8, 8, 8, 8, 8, 0.0008, 8, 8, 'F', 8, 1.25, 8, 'F', 8, 0.08, 8, 'S', 8, 8, 0.08, 0.08, 'S', 'S', 0.08, 0.08, 0.999999, 8, 0.08, 8, 0.08, 8, 0.8, 'F', 'S', 0.08, 8, 0.08, 0.08, 0.08);


