

CREATE TABLE agency_equalized_valuations (
    id BIGSERIAL PRIMARY KEY,
    agency_number VARCHAR(9) UNIQUE,
    annexed_property_equalized_value BIGINT,
    burden_percent DECIMAL(5,2),
    connecting_agency1 VARCHAR(9),
    connecting_agency2 VARCHAR(9),
    connecting_agency3 VARCHAR(9),
    connecting_agency4 VARCHAR(9),
    cook_county_air_pollution_value BIGINT,
    cook_county_railroad_value BIGINT,
    cook_county_real_estate_value BIGINT,
    cook_county_use_tax_value BIGINT,
    de_kalb_county_equalized_value BIGINT,
    disconnected_property_equalized_value BIGINT,
    disconnected_tif_difference BIGINT,
    du_page_county_equalized_value BIGINT,
    grundy_county_equalized_value BIGINT,
    kane_county_equalized_value BIGINT,
    kankakee_county_equalized_value BIGINT,
    kendall_county_equalized_value BIGINT,
    la_salle_county_equalized_value BIGINT,
    lake_county_equalized_value BIGINT,
    limiting_tax_rate_override DECIMAL(9,6),
    livingston_county_equalized_value BIGINT,
    mc_henry_county_equalized_value BIGINT,
    new_property_equalized_value BIGINT,
    overlap_annexed_property_equalized_value BIGINT,
    overlap_disconnected_property_equalized_value BIGINT,
    overlap_disconnected_tif_difference BIGINT,
    overlap_new_property_equalized_value BIGINT,
    parent_agency1 VARCHAR(9),
    parent_agency2 VARCHAR(9),
    parent_agency3 VARCHAR(9),
    parent_agency4 VARCHAR(9),
    parent_agency5 VARCHAR(9),
    previous_tax_year1 INTEGER,
    previous_tax_year1_extension DECIMAL(13,2),
    previous_tax_year2 INTEGER,
    previous_tax_year2_extension DECIMAL(13,2),
    previous_tax_year3 INTEGER,
    previous_tax_year3_extension DECIMAL(13,2),
    tax_cap_indicator BOOLEAN,
    tax_year INTEGER,
    will_county_equalized_value BIGINT
);


CREATE TABLE frozen_valuations (
    id BIGSERIAL PRIMARY KEY,
    change_action_current_improvement_value BIGINT,
    change_action_current_land_value BIGINT,
    change_action_current_parcel_count BIGINT,
    change_action_current_total_value BIGINT,
    change_action_prior_improvement_value BIGINT,
    change_action_prior_land_value BIGINT,
    change_action_prior_parcel_count BIGINT,
    change_action_prior_total_value BIGINT,
    current_improvement_value BIGINT,
    current_land_value BIGINT,
    current_parcel_count BIGINT,
    current_total_value BIGINT,
    division_number VARCHAR(14) UNIQUE,
    no_change_action_current_improvement_value BIGINT,
    no_change_action_current_land_value BIGINT,
    no_change_action_current_parcel_count BIGINT,
    no_change_action_current_total_value BIGINT,
    no_change_action_prior_improvement_value BIGINT,
    no_change_action_prior_land_value BIGINT,
    no_change_action_prior_parcel_count BIGINT,
    no_change_action_prior_total_value BIGINT,
    prior_improvement_value BIGINT,
    prior_land_value BIGINT,
    prior_parcel_count BIGINT,
    prior_total_value BIGINT,
    proposed_actual_value BIGINT,
    proposed_current288_value BIGINT,
    proposed_expired288_value BIGINT,
    proposed_improvement_value BIGINT,
    proposed_total_value BIGINT
);



